# -*- coding: utf-8 -*-
"""PalmerPenguinsM4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dqFSHrngftONy1f4yPhhAxbd7hMZgRi
"""

# PalmerPenguinsM4.py
# Kyler Dulaney
# 9/27/2026
# Uses branches to explore Palmer Penguin statistics.

import math

# constants representing the species and counts
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# lists containing related penguin data
species_names = [
   SP_CHINSTRAP,
   SP_GENTOO,
   SP_ADELIE
]

species_counts = [
   NUM_CHINSTRAP,
   NUM_GENTOO,
   NUM_ADELIE
]

# calculate dataset statistics
total_species = len(species_names)
total_penguins = sum(species_counts)

average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

# list containing species percentages
species_percentages = [
   chinstrap_percent,
   gentoo_percent,
   adelie_percent
]

largest_count = max(species_counts)
smallest_count = min(species_counts)

largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# output formatted statistics
print("Introducing the Palmer Penguins:")
print(f"\t{species_names[0]}!")
print(f"\t{species_names[1]}!")
print("and last but not least...")
print(f"\t{species_names[2]}!")
print()

print(f"There are a total of {total_species} penguin species in this dataset.")
print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is {average_penguins:.1f}.")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")

print(f"{species_names[0]}: {species_counts[0]} ({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_counts[1]} ({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_counts[2]} ({adelie_percent:.2f}%)")

print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")

# prompt the user to select a species
print()
print("Explore a species:")
species_choice = input("Enter Chinstrap, Gentoo, or Adelie: ")

# validate the species selection
if species_choice not in species_names:
   print(f"{species_choice} is not one of the species in this dataset.")
else:
   # determine the selected species
   if species_choice == species_names[0]:
      selected_index = 0
   elif species_choice == species_names[1]:
      selected_index = 1
   else:
      selected_index = 2

   selected_species = species_names[selected_index]
   selected_count = species_counts[selected_index]
   selected_percent = species_percentages[selected_index]

   # classify the selected species
   if selected_percent < 25:
      size_category = "small"
   elif (selected_percent >= 25) and (selected_percent < 40):
      size_category = "medium"
   else:
      size_category = "large"

   # determine the species position
   if (selected_species == largest_species) or \
      (selected_species == smallest_species):
      if selected_species == largest_species:
         position_description = "largest"
      else:
         position_description = "smallest"
   else:
      position_description = "middle-sized"

   # compare the selected count to the average
   average_position = "above" if selected_count > average_penguins else "below"

   # output selected species statistics
   print(f"{selected_species} has {selected_count} observations, representing {selected_percent:.2f}% of the dataset.")
   print(f"{selected_species} is classified as a {size_category} species group.")
   print(f"{selected_species} is the {position_description} species group.")
   print(f"Its observation count is {average_position} the dataset average of {average_penguins:.1f}.")